# config.yaml

ollama_model: "llama3"
chunk_size: 500
similarity_threshold: 0.75

neo4j:
  uri: "bolt://localhost:7687"
  user: "neo4j"
  password: "your_password"

weights:
  recall:
    K: 1.0        # Base score for fact existence
    c: 1.5        # Multiplier if relation matches
  precision:
    L: 1.0        # Base score for correct fact
    m: 1.5        # Multiplier if relation matches
    N: 2.0        # Penalty for hallucinated facts

export:
  json: true
  csv: true
  path: "./results/"